# Project Information
site_name: Maghreb vACC Documentation
site_url: https://docs.vatsim.ma
site_author: Ali Badreldeen & Bobbie Chell
edit_uri: ""
copyright: Copyright © 2023 Maghreb vACC

plugins:
  - search
  - awesome-pages
  - mike
  - git-revision-date-localized
  
# Configuration
theme:
  name: material
  font:
    text: Lato
  palette:
    scheme: marvacc
  logo: https://cdn.discordapp.com/attachments/991795403093721108/1118961763577237514/test.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc
    - breadcrumbs
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.tracking    
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
  favicon: https://cdn.discordapp.com/attachments/991795403093721108/1118961763577237514/test.png

extra_css:
  - stylesheets/marvacc.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/maghrebvacc/
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/MaghrebvACC
    - icon: fontawesome/brands/discord
      link: https://community.vatsim.net/servers
    - icon: material/home
      link: https://vatsim.ma
      name: Home
  version:
    provider: mike

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences